
#################################### global configure #######################################

username: xcq2000
baseurl: /#
markdown: redcarpet
safe: false
highlighter: pygments
title: Thinking in Robot
description:  I don't want to survive, I want to live ---- WALL.E
theme: midnight
disqusname: xcq2000

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine, kunka
# those themes are all come from GitHub Pages Themes
