# Site settings
title: Thinking in robot
tagline: "I don't want to survive, I want to live -- by Wall-E"
# email: your-email@domain.com
description: "The Northern Lights"
baseurl: ""
url: "http://blog.robotsns.com"

# Build settings
markdown: kramdown
permalink: pretty
