
#################################### global configure #######################################

username: xcq2000
baseurl: /blog
markdown: redcarpet
safe: false
highlighter: pygments
title: 机器人的思考
description:  瓦力：伊娃!
theme: hack
disqusname: xcq2000

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine, kunka
# those themes are all come from GitHub Pages Themes
